name: "[sync] terraform sync for <ENV>"
run-name: "[sync] terraform sync for ${{ github.ref_name }}"

on:
  pull_request:
    branches:
      - env/*
    types:
      - closed

jobs:
  terraform-apply:
    if: github.event.pull_request.merged == true

    runs-on: azure-integrated-runner-01

    environment: ${{ github.ref_name }}

    defaults:
      run:
        shell: bash
        working-directory: terraform/

    permissions:
      id-token: write

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - name: Download Terraform plan from AZ Blob Storage
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_IAC_SA }} \
            --name terraform.plan.PR#${{ github.event.pull_request.number }} \
            --container-name tfplan \
            --file terraform.plan \
            --auth-mode login

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.AZURE_IAC_RG }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_IAC_SA }}"

      - name: Terraform Apply
        run: |
          terraform apply \
            -var="AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" \
            -var="AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -auto-approve terraform.plan

      - name: Cleanup AZ Blob Storage
        if: always()
        run: |
          az storage blob delete \
            --account-name ${{ secrets.AZURE_IAC_SA }} \
            --name terraform.plan.PR#${{ github.event.pull_request.number }} \
            --container-name tfplan \
            --delete-snapshots include \
            --auth-mode login
